application: smart-snippets
version: 1
runtime: go
api_version: go1

handlers:
- url: stylesheets
  static_dir: static/stylesheets

- url: /javascript
  static_dir: static/javascript

- url: /.*
  script: _go_app  